/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_COMMONAPI_Can_Transceiver_PROXY_HPP_
#define V0_COMMONAPI_Can_Transceiver_PROXY_HPP_

#include <v0/commonapi/CanTransceiverProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/AttributeExtension.hpp>
#include <CommonAPI/Factory.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {

template <typename ... _AttributeExtensions>
class CanTransceiverProxy
    : virtual public CanTransceiver,
      virtual public CanTransceiverProxyBase,
      virtual public _AttributeExtensions... {
public:
    CanTransceiverProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~CanTransceiverProxy();

    typedef CanTransceiver InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Returns the wrapper class that provides access to the attribute speed.
     */
    virtual SpeedAttribute& getSpeedAttribute() {
        return delegate_->getSpeedAttribute();
    }
    /**
     * Returns the wrapper class that provides access to the attribute rpm.
     */
    virtual RpmAttribute& getRpmAttribute() {
        return delegate_->getRpmAttribute();
    }
    /**
     * Returns the wrapper class that provides access to the attribute sonarFront.
     */
    virtual SonarFrontAttribute& getSonarFrontAttribute() {
        return delegate_->getSonarFrontAttribute();
    }
    /**
     * Returns the wrapper class that provides access to the attribute sonarRear.
     */
    virtual SonarRearAttribute& getSonarRearAttribute() {
        return delegate_->getSonarRearAttribute();
    }
    /**
     * Returns the wrapper class that provides access to the attribute distances.
     */
    virtual DistancesAttribute& getDistancesAttribute() {
        return delegate_->getDistancesAttribute();
    }



 private:
    std::shared_ptr< CanTransceiverProxyBase> delegate_;
};

typedef CanTransceiverProxy<> CanTransceiverProxyDefault;

namespace CanTransceiverExtensions {
    template <template <typename > class _ExtensionType>
    class SpeedAttributeExtension {
     public:
        typedef _ExtensionType< CanTransceiverProxyBase::SpeedAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< CanTransceiverProxyBase::SpeedAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        SpeedAttributeExtension(CanTransceiverProxyBase& proxy): attributeExtension_(proxy.getSpeedAttribute()) {
        }
    
        inline extension_type& getSpeedAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

    template <template <typename > class _ExtensionType>
    class RpmAttributeExtension {
     public:
        typedef _ExtensionType< CanTransceiverProxyBase::RpmAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< CanTransceiverProxyBase::RpmAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        RpmAttributeExtension(CanTransceiverProxyBase& proxy): attributeExtension_(proxy.getRpmAttribute()) {
        }
    
        inline extension_type& getRpmAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

    template <template <typename > class _ExtensionType>
    class SonarFrontAttributeExtension {
     public:
        typedef _ExtensionType< CanTransceiverProxyBase::SonarFrontAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< CanTransceiverProxyBase::SonarFrontAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        SonarFrontAttributeExtension(CanTransceiverProxyBase& proxy): attributeExtension_(proxy.getSonarFrontAttribute()) {
        }
    
        inline extension_type& getSonarFrontAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

    template <template <typename > class _ExtensionType>
    class SonarRearAttributeExtension {
     public:
        typedef _ExtensionType< CanTransceiverProxyBase::SonarRearAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< CanTransceiverProxyBase::SonarRearAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        SonarRearAttributeExtension(CanTransceiverProxyBase& proxy): attributeExtension_(proxy.getSonarRearAttribute()) {
        }
    
        inline extension_type& getSonarRearAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

    template <template <typename > class _ExtensionType>
    class DistancesAttributeExtension {
     public:
        typedef _ExtensionType< CanTransceiverProxyBase::DistancesAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< CanTransceiverProxyBase::DistancesAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        DistancesAttributeExtension(CanTransceiverProxyBase& proxy): attributeExtension_(proxy.getDistancesAttribute()) {
        }
    
        inline extension_type& getDistancesAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

} // namespace CanTransceiverExtensions

//
// CanTransceiverProxy Implementation
//
template <typename ... _AttributeExtensions>
CanTransceiverProxy<_AttributeExtensions...>::CanTransceiverProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< CanTransceiverProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< CanTransceiverProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
CanTransceiverProxy<_AttributeExtensions...>::~CanTransceiverProxy() {
}


template <typename ... _AttributeExtensions>
const CommonAPI::Address &CanTransceiverProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool CanTransceiverProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool CanTransceiverProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& CanTransceiverProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& CanTransceiverProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> CanTransceiverProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace commonapi
} // namespace v0

namespace CommonAPI {
template<template<typename > class _AttributeExtension>
struct DefaultAttributeProxyHelper< ::v0::commonapi::CanTransceiverProxy,
    _AttributeExtension> {
    typedef typename ::v0::commonapi::CanTransceiverProxy<
            ::v0::commonapi::CanTransceiverExtensions::SpeedAttributeExtension<_AttributeExtension>, 
            ::v0::commonapi::CanTransceiverExtensions::RpmAttributeExtension<_AttributeExtension>, 
            ::v0::commonapi::CanTransceiverExtensions::SonarFrontAttributeExtension<_AttributeExtension>, 
            ::v0::commonapi::CanTransceiverExtensions::SonarRearAttributeExtension<_AttributeExtension>, 
            ::v0::commonapi::CanTransceiverExtensions::DistancesAttributeExtension<_AttributeExtension>
    > class_t;
};
}


// Compatibility
namespace v0_1 = v0;

#endif // V0_COMMONAPI_Can_Transceiver_PROXY_HPP_
