/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_COMMONAPI_Jetson_PROXY_HPP_
#define V0_COMMONAPI_Jetson_PROXY_HPP_

#include <v0/commonapi/JetsonProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/AttributeExtension.hpp>
#include <CommonAPI/Factory.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {

template <typename ... _AttributeExtensions>
class JetsonProxy
    : virtual public Jetson,
      virtual public JetsonProxyBase,
      virtual public _AttributeExtensions... {
public:
    JetsonProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~JetsonProxy();

    typedef Jetson InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Returns the wrapper class that provides access to the attribute steering.
     */
    virtual SteeringAttribute& getSteeringAttribute() {
        return delegate_->getSteeringAttribute();
    }
    /**
     * Returns the wrapper class that provides access to the attribute throttle.
     */
    virtual ThrottleAttribute& getThrottleAttribute() {
        return delegate_->getThrottleAttribute();
    }



 private:
    std::shared_ptr< JetsonProxyBase> delegate_;
};

typedef JetsonProxy<> JetsonProxyDefault;

namespace JetsonExtensions {
    template <template <typename > class _ExtensionType>
    class SteeringAttributeExtension {
     public:
        typedef _ExtensionType< JetsonProxyBase::SteeringAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< JetsonProxyBase::SteeringAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        SteeringAttributeExtension(JetsonProxyBase& proxy): attributeExtension_(proxy.getSteeringAttribute()) {
        }
    
        inline extension_type& getSteeringAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

    template <template <typename > class _ExtensionType>
    class ThrottleAttributeExtension {
     public:
        typedef _ExtensionType< JetsonProxyBase::ThrottleAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< JetsonProxyBase::ThrottleAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        ThrottleAttributeExtension(JetsonProxyBase& proxy): attributeExtension_(proxy.getThrottleAttribute()) {
        }
    
        inline extension_type& getThrottleAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

} // namespace JetsonExtensions

//
// JetsonProxy Implementation
//
template <typename ... _AttributeExtensions>
JetsonProxy<_AttributeExtensions...>::JetsonProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< JetsonProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< JetsonProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
JetsonProxy<_AttributeExtensions...>::~JetsonProxy() {
}


template <typename ... _AttributeExtensions>
const CommonAPI::Address &JetsonProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool JetsonProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool JetsonProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& JetsonProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& JetsonProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> JetsonProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace commonapi
} // namespace v0

namespace CommonAPI {
template<template<typename > class _AttributeExtension>
struct DefaultAttributeProxyHelper< ::v0::commonapi::JetsonProxy,
    _AttributeExtension> {
    typedef typename ::v0::commonapi::JetsonProxy<
            ::v0::commonapi::JetsonExtensions::SteeringAttributeExtension<_AttributeExtension>, 
            ::v0::commonapi::JetsonExtensions::ThrottleAttributeExtension<_AttributeExtension>
    > class_t;
};
}


// Compatibility
namespace v0_1 = v0;

#endif // V0_COMMONAPI_Jetson_PROXY_HPP_
