/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.14.v202310241606.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V0_COMMONAPI_CAN_TRANSCEIVER_SOMEIP_STUB_ADAPTER_HPP_
#define V0_COMMONAPI_CAN_TRANSCEIVER_SOMEIP_STUB_ADAPTER_HPP_

#include <v0/commonapi/CanTransceiverStub.hpp>
#include <v0/commonapi/CanTransceiverSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {

template <typename _Stub = ::v0::commonapi::CanTransceiverStub, typename... _Stubs>
class CanTransceiverSomeIPStubAdapterInternal
    : public virtual CanTransceiverStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< CanTransceiverSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> CanTransceiverSomeIPStubAdapterHelper;

    ~CanTransceiverSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        CanTransceiverSomeIPStubAdapterHelper::deinit();
    }

    void fireSpeedAttributeChanged(const uint32_t &_value);
    
    void fireRpmAttributeChanged(const uint32_t &_value);
    
    void fireSonarFrontAttributeChanged(const uint32_t &_value);
    
    void fireSonarRearAttributeChanged(const uint32_t &_value);
    
    void fireDistancesAttributeChanged(const ::v0::commonapi::CanTransceiver::SonarArrayStruct &_value);
    
    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::commonapi::CanTransceiverStub,
        CommonAPI::Version
    > getCanTransceiverInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::commonapi::CanTransceiverStub,
        uint32_t,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>
    > getSpeedAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::commonapi::CanTransceiverStub,
        uint32_t,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>
    > getRpmAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::commonapi::CanTransceiverStub,
        uint32_t,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>
    > getSonarFrontAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::commonapi::CanTransceiverStub,
        uint32_t,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>
    > getSonarRearAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::commonapi::CanTransceiverStub,
        ::v0::commonapi::CanTransceiver::SonarArrayStruct,
        ::v0::commonapi::CanTransceiver_::SonarArrayStructDeployment_t
    > getDistancesAttributeStubDispatcher;
    
    CanTransceiverSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        CanTransceiverSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< CanTransceiverStub>(_stub)),
        getCanTransceiverInterfaceVersionStubDispatcher(&CanTransceiverStub::lockInterfaceVersionAttribute, &CanTransceiverStub::getInterfaceVersion, false, true),
        getSpeedAttributeStubDispatcher(
            &::v0::commonapi::CanTransceiverStub::lockSpeedAttribute,
            &::v0::commonapi::CanTransceiverStub::getSpeedAttribute,
            false,
            _stub->hasElement(0))
        ,
        getRpmAttributeStubDispatcher(
            &::v0::commonapi::CanTransceiverStub::lockRpmAttribute,
            &::v0::commonapi::CanTransceiverStub::getRpmAttribute,
            false,
            _stub->hasElement(1))
        ,
        getSonarFrontAttributeStubDispatcher(
            &::v0::commonapi::CanTransceiverStub::lockSonarFrontAttribute,
            &::v0::commonapi::CanTransceiverStub::getSonarFrontAttribute,
            false,
            _stub->hasElement(2))
        ,
        getSonarRearAttributeStubDispatcher(
            &::v0::commonapi::CanTransceiverStub::lockSonarRearAttribute,
            &::v0::commonapi::CanTransceiverStub::getSonarRearAttribute,
            false,
            _stub->hasElement(3))
        ,
        getDistancesAttributeStubDispatcher(
            &::v0::commonapi::CanTransceiverStub::lockDistancesAttribute,
            &::v0::commonapi::CanTransceiverStub::getDistancesAttribute,
            false,
            _stub->hasElement(4))
    {
        CanTransceiverSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xce5) }, &getSpeedAttributeStubDispatcher );
        CanTransceiverSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xd49) }, &getRpmAttributeStubDispatcher );
        CanTransceiverSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xdad) }, &getSonarFrontAttributeStubDispatcher );
        CanTransceiverSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xdae) }, &getSonarRearAttributeStubDispatcher );
        CanTransceiverSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xdaf) }, &getDistancesAttributeStubDispatcher );
        std::shared_ptr<CommonAPI::SomeIP::ClientId> itsClient = std::make_shared<CommonAPI::SomeIP::ClientId>();

        // Provided events/fields
        if (_stub->hasElement(0)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0xce4)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x80e8), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE);
            fireSpeedAttributeChanged(std::dynamic_pointer_cast< ::v0::commonapi::CanTransceiverStub>(_stub)->getSpeedAttribute(itsClient));
        }

        if (_stub->hasElement(1)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0xd48)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x84d0), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE);
            fireRpmAttributeChanged(std::dynamic_pointer_cast< ::v0::commonapi::CanTransceiverStub>(_stub)->getRpmAttribute(itsClient));
        }

        if (_stub->hasElement(2)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0xdac)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x88b8), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE);
            fireSonarFrontAttributeChanged(std::dynamic_pointer_cast< ::v0::commonapi::CanTransceiverStub>(_stub)->getSonarFrontAttribute(itsClient));
        }

        if (_stub->hasElement(3)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0xdac)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x88b9), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE);
            fireSonarRearAttributeChanged(std::dynamic_pointer_cast< ::v0::commonapi::CanTransceiverStub>(_stub)->getSonarRearAttribute(itsClient));
        }

        if (_stub->hasElement(4)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0xdac)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x88ba), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE);
            fireDistancesAttributeChanged(std::dynamic_pointer_cast< ::v0::commonapi::CanTransceiverStub>(_stub)->getDistancesAttribute(itsClient));
        }

    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

template <typename _Stub, typename... _Stubs>
void CanTransceiverSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireSpeedAttributeChanged(const uint32_t &_value) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployedValue(_value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0x80e8),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void CanTransceiverSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireRpmAttributeChanged(const uint32_t &_value) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployedValue(_value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0x84d0),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void CanTransceiverSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireSonarFrontAttributeChanged(const uint32_t &_value) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployedValue(_value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0x88b8),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void CanTransceiverSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireSonarRearAttributeChanged(const uint32_t &_value) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployedValue(_value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0x88b9),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void CanTransceiverSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireDistancesAttributeChanged(const ::v0::commonapi::CanTransceiver::SonarArrayStruct &_value) {
    CommonAPI::Deployable< ::v0::commonapi::CanTransceiver::SonarArrayStruct, ::v0::commonapi::CanTransceiver_::SonarArrayStructDeployment_t> deployedValue(_value, static_cast< ::v0::commonapi::CanTransceiver_::SonarArrayStructDeployment_t* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ::v0::commonapi::CanTransceiver::SonarArrayStruct,
                ::v0::commonapi::CanTransceiver_::SonarArrayStructDeployment_t
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0x88ba),
        false,
        deployedValue
    );
}


template <typename _Stub, typename... _Stubs>
void CanTransceiverSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {

}

template <typename _Stub, typename... _Stubs>
void CanTransceiverSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {

}

template <typename _Stub = ::v0::commonapi::CanTransceiverStub, typename... _Stubs>
class CanTransceiverSomeIPStubAdapter
    : public CanTransceiverSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    CanTransceiverSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          CanTransceiverSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace commonapi
} // namespace v0

#endif // V0_COMMONAPI_Can_Transceiver_SOMEIP_STUB_ADAPTER_HPP_
